ann: main.cpp NNLastRowFitness.hpp NNCheckerboardFitness.hpp NeuralNetwork.hpp HillClimber.hpp Individual.hpp Random.hpp VectorFitnessFunction.hpp VectorIndividual.hpp
	g++ main.cpp -lm -o ann

clean:
	rm ann *.csv *.pdf
