robo: main.cpp TableRobot.hpp TableSimulator.hpp TouchSensor.hpp
	g++ -I"/Users/nshetty/Code/bullet/install/include/OpenGL" -I"/Users/nshetty/Code/bullet/install/include/bullet" -L"/Users/nshetty/Code/bullet/install/lib" -framework GLUT -framework OpenGL -lOpenGLSupport -lBulletDynamics -lBulletCollision -lLinearMath main.cpp -o robo

clean:
	rm robo *.csv *.pdf
